### ISSUE TITLE
Tracking different estimators and their status, for 0.6.2 release

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TransferEntropy.jl#22]
# A common transfer entropy estimator inferface.

For the 0.6.2 release, we'll focus on having low-level estimators that require active thinking by the user. The estimators should be on the form 

```
transferentropy_estimator(E::AbstractEmbedding, 
                            ϵ::Union{Int, Float64, Vector{Float64}},
                            v::TEVars) -> Float64
```
where `E` is a state space reconstruction constructed with high enough dimension that it is actually an embedding, `ϵ` gives the binning scheme and `v` indicates which variables/columns of the embedding should be considered in which marginals during the transfer entropy computation. 

## Implementation status
The different algorithms and their implementation status are as follows.

- [x] `transferentropy_transferoperator_visitfreq`, or `tetofreq`. This estimator obtains transition probabilities from the transfer operator. Estimation of the transfer operator, from which the invariant measure over the reconstructed state space is derived, is done using [PerronFrobenius.jl](https://github.com/kahaaga/PerronFrobenius.jl). 
- [x] `transferentropy_visitfreq`, or `tefreq`. This estimator obtains probabilities by partitioning the reconstructed state space into rectangular boxes, counting the visits to each bin, and taking the normalised visitation frequencies as estimates of the probabilities. Based on [Verdes, P. F. "Assessing causality from multivariate time series." Physical Review E 72.2 (2005): 026222](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.72.026222). 
- [x] `transferentropy_kraskov`, `tekNN`, or`tekraskov`. This estimator computes transfer entropy as the sum of two mutual information terms, computing the Kraskov estimator for mutual information.
- [x] KDE estimator.

**Comment by kahaaga** [comment]
Done in #58 .
